# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 220579a651183176d9b7905bd8b0f5d665d43e39cfed709bcb787da645a87a5d974f9c11625d6f7fff0d4d2c9b661301b96669d9c9acefa3f9b56a348f252c64

test:
  secret_key_base: 46e6e8dba865d350bf00377932d23053df820c367021ae097bd698db236849506c53f20fef0653b3f4413cccd65d75ad6f558e8cdf7a202c18840371fc841bed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
